# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRP', models.CharField(max_length=100)),
                ('PRJ', models.CharField(max_length=100)),
                ('Organism', models.CharField(max_length=100)),
                ('Abstract', models.CharField(max_length=1000)),
                ('Url', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
