# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRP', models.CharField(max_length=100)),
                ('PRJ', models.CharField(max_length=100)),
                ('Organism', models.CharField(default='NA', max_length=100)),
                ('Sample', models.CharField(max_length=100)),
                ('Runs', models.CharField(max_length=200)),
                ('Instrument', models.CharField(default='NA', max_length=100)),
                ('Release', models.IntegerField(default=2018)),
                ('Sex', models.CharField(default='NA', max_length=100)),
                ('Fluid', models.CharField(max_length=100)),
                ('Extraction', models.CharField(default='NA', max_length=100)),
                ('Library', models.CharField(default='NA', max_length=100)),
                ('Healthy', models.CharField(default='NA', max_length=100)),
                ('Cancer', models.CharField(default='NA', max_length=100)),
                ('Exosome', models.CharField(default='False', max_length=100)),
                ('Desc', models.CharField(default='False', max_length=100)),
            ],
        ),
    ]
