# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180626_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Sex',
            field=models.CharField(max_length=100),
        ),
    ]
